---
- name: Install {{ docker_package }}
  package:
    name: "{{ docker_package }}"
    state: present
  register: installed_docker
  retries: 30
  until: installed_docker is succeeded
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true
