---
- name: Check latest docker-compose version
  set_fact:
    compose_latest_version: >-
      {{ lookup('url', 'https://github.com/docker/compose/releases/latest') |
        regex_findall('download/([0-9]+[.][0-9]+[.][0-9]+)') | first }}
    when: compose_version == 'latest'
  changed_when: false

- name: Install Docker Compose v.{{ compose_latest_version | default(docker_compose_version) }}
  pip:
    name:  docker-compose
    version: '{{ compose_latest_version | default(docker_compose_version) }}'
    state: present
    executable: '{{ pip_executable }}'
    extra_args: --upgrade
  register: status
  until: status is succeeded
  become: true
