---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: docker.yml
  when: docker_install | bool

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: pip.yml
  when: pip_install | bool

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: deploy-compose.yml
  when: deploy_compose | bool
