---
- name: Install Pip dependencies
  apt:
    name: '{{ pip_dependencies }}'
    state: present
  register: status
  until: status is succeeded

- name: Install PIP modules
  pip:
    name: '{{ pip_install_packages }}'
    state: present
    executable: '{{ pip_executable }}'
    extra_args: --upgrade
  register: status
  until: status is succeeded
  become: true
